README.md
we should be encouraging users to require stable released versions, not `dev-master`. that is bad practice.  as long as you are following semantic versioning (which it appears you are) we can say we want anything in the major 2 version.
also a spelling fix
=> better composer dependency and spelling fixes

lib/EasyPost/EasyPost.php, lib/EasyPost/Requestor.php
This PR addresses Issue https://github.com/EasyPost/easypost-php/issues/54
This is a backwards-compatible change that adds the `EasyPost::setConnectTimeout()` and  `EasyPost::setResponseTimeout()` methods to allowing setting the number of milliseconds to wait for a connection and response, respectively,
These are needed because the default curl behavior is to wait indefinitely, which can cause services to stall under load.
**Usage**
If `connectTimeout` is set to `1000` it will wait up to one (1) second to connect to EasyPost. If this is set to zero (0) or null, then the default PHP curl behavior is maintained. Thus there is no BC break, because the defaults for these settings are both null.
Likewise, if `responseTimeout` is set to `5000` it will wait up to five (5) seconds, after the …
=> Add optional CURL timeouts setting

README.md
Fixed the Travis badge from `.org to .com` and made some additional README clarifications after looking through everything again.
=> Install info & Travis badge fixes on README

lib/EasyPost/Report.php, lib/EasyPost/Util.php, test/EasyPost/Test/ReportTest.php
Similar to our Python client library, the reports response is being double wrapped when it shouldn't. I've corrected that issue here and written a unit test.
For whatever reason, I cannot get the unit test of `assertInstanceOf` to pass for the `Refund` report... the problem is alluding me as the code is the exact same across all four reports. I'll need some help fixing that unit test before this will pass.
=> Fixed create report feature and added unit test

README.md
After looking into how we release PHP more, I noticed one other place where the version must be altered when releasing which is in the `EasyPost.php` file. This VERSION constant is used inside the headers so we know what CL version each request uses. 
The last few versions haven't had this constant bumped, mainly because it wasn't documented. I added a single clarifying step to the README so we'll remember moving forward.
=> Bumped version to 3.4.5 with README clarification

lib/EasyPost/EasyPostObject.php
Carriers cannot be deleted currently. This fixes the error found in #61 
Closes #61 
Closes #64 (difference here is no changes made to CHANGELOG as we'll do a release PR after)
=> Fixes the bug not allowing for carrier deletion

lib/EasyPost/Shipment.php
Starting soon in the future,get_rates() will always be read-only (as you would expect from a GET), and re-rating will be triggered through the new regenerate_rates() function. This adds the new function. No change has occurred to get_rates() yet.
=> add regenerate_rates method

.github/workflows/ci.yml, .gitignore, README.md, composer.json, composer.lock, examples/carrier_account_management.php, examples/pickups.php, examples/users.php, examples/webhooks.php, lib/EasyPost/Address.php, lib/EasyPost/Batch.php, lib/EasyPost/Event.php, lib/EasyPost/Shipment.php, lib/EasyPost/Tracker.php, phpcs.xml, test/EasyPost/Test/ReportTest.php
This PR:
* Swaps the linter
* Lints the entire project
* Adds missing composer commands for convenient running of `lint`, `fix`, and `test`
* Checks in the missing (and ignored) `composer.lock` file so all devs get the same set of dependencies
* Pins `phpunit/php-token-stream` to `v3` to fix build on `PHP 7.2`
* Removes the API key from the README
About a year ago, I introduced a couple dev dependencies that we should remove in favor of better supported and more mainstream alternatives.
The dependencies initially added are `php-cs-fixer` which is a linter/formatter that will automatically correct code. This is too invasive (without an accompanying linter) as it assumes the style on our behalf. There was also `phplint` which does the absolute bare minimum (only checks syntax errors but …
=> fix(lint): Swaps linter and lints project

lib/EasyPost/Shipment.php, test/EasyPost/Test/ShipmentTest.php
Adds the new `/smartrate` endpoint/method on the `Shipment` object.
Simply call `get_smartrates` on the shipment object and you'll be returned a list of smartrates like so:
```json
[
{
"carrier": "USPS",
"carrier_account_id": "ca_123...",
"created_at": "2021-05-04T21:15:59Z",
"currency": "USD",
"delivery_date": null,
"delivery_date_guaranteed": true,
"delivery_days": null,
"est_delivery_days": null,
"id": "rate_123...",
"list_currency": null,
"list_rate": null,
"mode": "test",
"object": "Rate",
"rate": 0.01,
"retail_currency": null,
"retail_rate": null,
"service": "First",
"shipment_id": "shp_123",
"time_in_transit": {
"percentile_50": 2,
"percentile_75": 3,
"percentile_85": 4,
"percentile_90": 4,
"percentile_95": 4,
"percentile_97": 4,
"percentile_99": 4
},
"updated_at": …
```
=> feat: adds smartrate functionality

CHANGELOG.md, lib/EasyPost/Requestor.php
We haven't used the `contact@easypost.com` email for some time for support inquiries, correct it to `support@easypost.com`.
=> fix: corrects support email in error messages

.github/workflows/ci.yml, .gitignore, README.md, composer.json, composer.lock, phpunit.xml.dist, test/EasyPost/Test/AddressTest.php, test/EasyPost/Test/ParcelTest.php, test/EasyPost/Test/ReportTest.php, test/EasyPost/Test/ShipmentTest.php, test/bootstrap.php, test/cassettes/addresses/create.yml, test/cassettes/addresses/retrieve.yml, test/cassettes/parcels/create.yml, test/cassettes/parcels/retrieve.yml, test/cassettes/reports/createPaymentLogReport.yml, test/cassettes/reports/createRefundReport.yml, test/cassettes/reports/createShipmentInvoiceReport.yml, test/cassettes/reports/createShipmentReport.yml, test/cassettes/reports/createTrackerReport.yml, test/cassettes/reports/retrievePaymentLogReport.yml, test/cassettes/reports/retrieveRefundReport.yml, test/cassettes/reports/retrieveShipmentReport.yml, test/cassettes/reports/retrieveTrackerReport.yml, test/cassettes/shipments/buy.yml, test/cassettes/shipments/create.yml, test/cassettes/shipments/retrieve.yml, test/cassettes/shipments/smartrates.yml
This PR adds long overdue `VCR` support to the PHP client library. This carries multiple benefits:
1. Consistent tests. We can now replay HTTP responses instead of hitting the live API on every test run
2. We can remove the poorly constructed "random date" logic in the reports tests which is now much less flakey
3. We can assert real values for items such as SmartRate integers on delivery days because we can return the same value each time
This PR includes another library called `php-vcr-sanitizer` that I personally contributed to that redacts items such as the `Authorization` header so we don't expose API keys in the cassettes. This library is needed because `php-vcr` is not privacy conscious out of the box.
The hardcoded API Key was removed from tests and replaced with `getenv` to grab …
=> feat: adds VCR support to tests

lib/EasyPost/Requestor.php, test/EasyPost/Test/ReportTest.php, test/EasyPost/Test/ShipmentTest.php, test/cassettes/addresses/create.yml, test/cassettes/addresses/retrieve.yml, test/cassettes/parcels/create.yml, test/cassettes/parcels/retrieve.yml, test/cassettes/reports/createPaymentLogReport.yml, test/cassettes/reports/createRefundReport.yml, test/cassettes/reports/createShipmentInvoiceReport.yml, test/cassettes/reports/createShipmentReport.yml, test/cassettes/reports/createTrackerReport.yml, test/cassettes/reports/retrievePaymentLogReport.yml, test/cassettes/reports/retrieveRefundReport.yml, test/cassettes/reports/retrieveShipmentReport.yml, test/cassettes/reports/retrieveTrackerReport.yml, test/cassettes/shipments/buy.yml, test/cassettes/shipments/create.yml, test/cassettes/shipments/retrieve.yml, test/cassettes/shipments/smartrates.yml
JSON encodes bodies instead of formencoding them, this will pave the way for new features such as `tax_identifiers`.
We leave GET and DELETE requests alone with url encoding (since you cannot pass a POST body on those items) and JSON encode POST/PATCH/PUT requests instead of form encoding them. Refactored a couple items and renamed for a clearer experience.
Re-recorded all cassettes and they worked great.
=> fix: json encode bodies instead of urlencoding

CHANGELOG.md, lib/EasyPost/EasyPost.php, lib/EasyPost/Requestor.php
This sets a default timeout of 30 seconds for connections and 60 seconds for requests. Currently, there is no timeout at all set and connections will stay open forever (or until the EasyPost servers kill them off).
60 seconds was chosen as it's long enough not to be hostile but short enough to not leave connections open for vast amounts of time.
Similarly, `CURLE_OPERATION_TIMEOUTED` is aliased to `CURLE_OPERATION_TIMEDOUT` which is now the proper way of writing this option. See https://www.php.net/manual/en/curl.constants.php for details.
This was end to end tested by setting the timeout to `1ms` and receiving a timeout error, then removing the timeout call to use the new default which sent the request through under 60 seconds.
=> chore: sets a default timeout of 60 seconds on requests

.github/workflows/ci.yml
PHP 8.1 just came out. This adds PHP 8.1 to the matrix of versions to test against.
=> chore: test library against PHP 8.1

examples/addresses.php, examples/addresses_verify.php, examples/addresses_verify_failure.php, examples/addresses_verify_strict_failure.php, examples/batches.php, examples/carrier_account_management.php, examples/customsinfos.php, examples/insurance.php, examples/intl_shipments.php, examples/order_international.php, examples/orders.php, examples/parcels.php, examples/pickups.php, examples/rates.php, examples/readme.php, examples/refunds.php, examples/reports.php, examples/scanforms.php, examples/shipment.php, examples/shipment_from_tracking_codes.php, examples/timeouts.php, examples/tracker_batch_create.php, examples/trackers.php, examples/users.php, examples/webhooks.php
Removes the remainder of the hard-coded API keys from example files.
=> chore: removes the remainder of API keys from examples

lib/EasyPost/EasyPostObject.php
Adds `#[\ReturnTypeWillChange]` to some EasyPostObject methods to remove the deprecation warnings on PHP 8.1. The return type definitions will be required for PHP 9; however, because we will still be supporting PHP 7.3 for some time and the `mixed` return type which is required to fix this but not included until PHP 8 isn't possible at the moment, we'll temporarily ignore these deprecation notices until we drop support for PHP 7 altogether (I'd assume about the same time we adopt PHP 9 once it's out.)
Closes #124
=> fix: adds ReturnTypeWillChange to temporarily ignore deprecation warnings

CHANGELOG.md, README.md, composer.json, composer.lock
Bumps the minimum PHP version supported from 5.3 to 7.3 in an our ongoing efforts to modernize our libraries. The impact of this change should be minimal as the library already supports all core features of the API so we won't be cutting off legacy users from features. To prepare for other 8.x releases and eventually PHP 9, we need to update the minimum version to allow our dev dependencies to catch up.
=> chore: bumps the minimum PHP version supported from 5.3 to 7.3

lib/EasyPost/CarrierAccount.php, lib/EasyPost/EasyPostObject.php, lib/EasyPost/EasypostResource.php, lib/EasyPost/Error.php, lib/EasyPost/Report.php, lib/EasyPost/Shipment.php, lib/EasyPost/Tracker.php, lib/EasyPost/User.php, lib/EasyPost/Util.php, lib/EasyPost/Webhook.php, test/EasyPost/Test/WebhookTest.php, test/cassettes/webhooks/create.yml, test/cassettes/webhooks/delete.yml, test/cassettes/webhooks/retrieve.yml
Cleans up a few deprecated syntax issues (calling static vs non-static methods incorrectly, remove unused parameters) and cleans up a few comments.
I added webhook tests to ensure the switching of static/non-static delete/update calls still works.
=> chore: fix syntax errors and clean up comments

test/EasyPost/AddressTest.php, test/EasyPost/BatchTest.php, test/EasyPost/CarrierAccountTest.php, test/EasyPost/CustomsInfoTest.php, test/EasyPost/CustomsItemTest.php, test/EasyPost/EasyPostTest.php, test/EasyPost/ErrorTest.php, test/EasyPost/OrderTest.php, test/EasyPost/ParcelTest.php, test/EasyPost/PickupTest.php, test/EasyPost/RefundTest.php, test/EasyPost/ReportTest.php, test/EasyPost/ShipmentTest.php, test/EasyPost/TrackerTest.php, test/EasyPost/UserTest.php, test/EasyPost/WebhookTest.php
Swaps the order of all `assertEquals` tests to be `expected`, then `actual` like it should be.
Also found one `assertNotNull` that should have actually been an `assertEquals`.
=> fix: test assertEquals order

test/EasyPost/AddressTest.php, test/EasyPost/BatchTest.php, test/EasyPost/EventTest.php, test/EasyPost/InsuranceTest.php, test/EasyPost/RefundTest.php, test/EasyPost/ReportTest.php, test/EasyPost/ScanFormTest.php, test/EasyPost/ShipmentTest.php, test/EasyPost/TrackerTest.php
Adds `has_more` assertions to retrieving `all` records to ensure users can paginate properly.
=> chore: assert against has_more key for pagination

CHANGELOG.md, lib/EasyPost/Address.php, test/EasyPost/AddressTest.php, test/cassettes/addresses/verify.yml
* Removes the `params` from the `Address->verify()` method since it's non-static and unused
=> fix: removes the params from the Address->verify method

test/EasyPost/AddressTest.php, test/EasyPost/BatchTest.php, test/EasyPost/CarrierAccountTest.php, test/EasyPost/EventTest.php, test/EasyPost/InsuranceTest.php, test/EasyPost/OrderTest.php, test/EasyPost/RefundTest.php, test/EasyPost/ReportTest.php, test/EasyPost/ScanFormTest.php, test/EasyPost/ShipmentTest.php, test/EasyPost/TrackerTest.php, test/EasyPost/WebhookTest.php
Simplify the `all` tests by using `assertContainsOnlyInstancesOf` instead of iterating each record to assert the instance. This was also done in the Ruby lib. Has the added benefit of correcting a few bad variable names from copy/pasta.
=> fix: don't iterate all tests, use containsonlyinstanceof

test/EasyPost/ShipmentTest.php, test/cassettes/shipments/createWithIds.yml
Adds a test when only IDs are passed to object creation. This was brought up as a way to check behavior across all libs due to: https://github.com/EasyPost/easypost-node/issues/222
=> chore: add shipment ID test

CHANGELOG.md, lib/EasyPost/Report.php, test/EasyPost/ReportTest.php, test/cassettes/reports/all.yml, test/cassettes/reports/createCustomAdditionalColumnReport.yml, test/cassettes/reports/createCustomColumnReport.yml, test/cassettes/reports/createPaymentLogReport.yml, test/cassettes/reports/createRefundReport.yml, test/cassettes/reports/createShipmentInvoiceReport.yml, test/cassettes/reports/createShipmentReport.yml, test/cassettes/reports/createTrackerReport.yml, test/cassettes/reports/retrievePaymentLogReport.yml, test/cassettes/reports/retrieveRefundReport.yml, test/cassettes/reports/retrieveShipmentReport.yml, test/cassettes/reports/retrieveTrackerReport.yml
This PR:
- Adds support for specifying `columns` and `additional_columns` (both lists of strings) in the parameters dictionary passed into the `Report->create()` function.
Unfortunately, since the API response does not indicate the columns used for a report, the only way to ensure the report actually includes the columns requested would be to make a live API call, download the generated CSV report and parse its column headers. That is a complex unit test with many points of failure and prevents us from using VCR.
Instead, we simply assume that if no error is thrown during the API call to generate and retrieve the report, that the report contains the correct columns. If it doesn't, that constitutes a server-side error that is out of our control.
=> [feat] Support for `columns` and `additional_columns` on Report creation

test/EasyPost/ShipmentTest.php, test/cassettes/shipments/createEmptyObjects.yml
This PR adds a missing assertion for `tax_identifiers`
=> add assertion for tax_identifiers in shipment test.

README.md, test/EasyPost/Fixture.php, test/EasyPost/PickupTest.php, test/EasyPost/ReportTest.php, test/EasyPost/WebhookTest.php, test/cassettes/pickups/buy.yml, test/cassettes/pickups/cancel.yml, test/cassettes/pickups/create.yml, test/cassettes/pickups/retrieve.yml, test/cassettes/reports/all.yml, test/cassettes/reports/createCustomAdditionalColumnReport.yml, test/cassettes/reports/createCustomColumnReport.yml, test/cassettes/reports/createReport.yml, test/cassettes/reports/retrieveReport.yml
I was too trusting of VCR to play nice with dynamic dates in fixtures which broke the master branch build. Going back to hard-coded dates in the test suite but simplifying how many date fixtures we need so that recorded cassettes stay happy regardless of when it's run.
=> fix: test dates by hardcoding

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
We should standardize what information we collect from users reporting issues or requesting features to our client library repositories to streamline and enhance our ability to address issues.
This PR includes:
- Template for GitHub bug reports, collecting required information
- Template for GitHub feature requests
Preview the templates:
- Bug report: https://github.com/EasyPost/easypost-php/blob/issue_template/.github/ISSUE_TEMPLATE/bug_report.yml
- Feature request: https://github.com/EasyPost/easypost-php/blob/issue_template/.github/ISSUE_TEMPLATE/feature_request.yml
The templates includes some PHP-specific settings and repo-specific links. Once approved for this repository, this template will be altered accordingly and added to all other client library repositories.
=> Add bug report and feature request templates for issues

lib/EasyPost/EasypostResource.php, lib/EasyPost/Requestor.php, test/cassettes/carrier_accounts/create.yml, test/cassettes/carrier_accounts/delete.yml, test/cassettes/carrier_accounts/retrieve.yml, test/cassettes/carrier_accounts/update.yml, test/cassettes/users/update.yml
Removes the `PATCH` HTTP method as we don't use it in our API and replaces it with `PUT` since that's what our docs use (none of our other libs use PATCH either). Based on our docs, we will only partial update anyway meaning we are replicating a PATCH call even though it's PUT. Cleaning up the code here (no affect to a user) to simplify the codebase, reduce complexity, and remove confusion.
- Rerecorded cassettes
=> chore: replace patch method with put

CHANGELOG.md, lib/EasyPost/Order.php, lib/EasyPost/Pickup.php, lib/EasyPost/Shipment.php, lib/EasyPost/Util.php, test/EasyPost/Fixture.php, test/EasyPost/OrderTest.php, test/EasyPost/PickupTest.php, test/EasyPost/ShipmentTest.php, test/cassettes/orders/lowestRate.yml, test/cassettes/pickups/buy.yml, test/cassettes/pickups/cancel.yml, test/cassettes/pickups/create.yml, test/cassettes/pickups/lowestRate.yml, test/cassettes/pickups/retrieve.yml, test/cassettes/shipments/getLowestSmartrate.yml, test/cassettes/shipments/lowestRate.yml, test/cassettes/shipments/lowestSmartrate.yml
- Adds a `lowest_rate` function to Orders and Pickups
- Adds `Shipment::get_lowest_smartrate()` and `$shipment.lowest_smartrate()` functions
=> feat: adds lowest_rate to more objects

CHANGELOG.md, lib/EasyPost/Requestor.php, test/EasyPost/ErrorTest.php
The changes from #189 are found here with additional comments and tests. Cannot push to the original PR as it was not created off a branch and was on the master branch. These changes are backwards compatible while providing a bandaid fix for carriers like GSO/GLS.
=> fix: coerce array errors to strings if present

CHANGELOG.md, lib/EasyPost/Address.php, test/EasyPost/AddressTest.php, test/cassettes/addresses/createAndVerify.yml, test/cassettes/addresses/createVerify.yml, test/cassettes/addresses/createVerifyArray.yml, test/cassettes/addresses/createVerifyStrict.yml
Fixes a bug that required the values of `verify` and `verify_strict` params on an Address creation call to be arrays since passing `true` as a boolean is also valid (passing an array will continue to work but is no longer required)
- Updates unit tests to use boolean instead of an array
- Adds a new unit test to ensure that arrays continue to work (backwards compatible fix)
=> fix: address verify params no longer required to be arrays

test/EasyPost/AddressTest.php, test/EasyPost/BatchTest.php, test/EasyPost/Beta/EndShipperTest.php, test/EasyPost/BillingTest.php, test/EasyPost/CarrierAccountTest.php, test/EasyPost/CustomsInfoTest.php, test/EasyPost/CustomsItemTest.php, test/EasyPost/EasyPostTest.php, test/EasyPost/ErrorTest.php, test/EasyPost/EventTest.php, test/EasyPost/InsuranceTest.php, test/EasyPost/OrderTest.php, test/EasyPost/ParcelTest.php, test/EasyPost/PickupTest.php, test/EasyPost/RateTest.php, test/EasyPost/RefundTest.php, test/EasyPost/ReportTest.php, test/EasyPost/ScanFormTest.php, test/EasyPost/ShipmentTest.php, test/EasyPost/TrackerTest.php, test/EasyPost/UserTest.php, test/EasyPost/WebhookTest.php, test/cassettes/end_shipper/retrieve.yml, test/cassettes/end_shipper/update.yml
- Remove `return` docstrings for unit tests
- Remove EndShipper dependence on `testCreate`
- All unit tests pass as expected
=> Remove `return` docstrings for unit tests

lib/EasyPost/Address.php, lib/EasyPost/Batch.php, lib/EasyPost/Beta/EndShipper.php, lib/EasyPost/Billing.php, lib/EasyPost/EasypostResource.php, lib/EasyPost/Error.php, lib/EasyPost/Requestor.php, lib/EasyPost/Shipment.php, lib/EasyPost/Tracker.php, lib/EasyPost/Util.php, lib/EasyPost/Webhook.php, phpcs.xml, test/EasyPost/ErrorTest.php, test/EasyPost/ShipmentTest.php, test/EasyPost/TrackerTest.php, test/EasyPost/WebhookTest.php
Switches all use of double quotes (for normal strings without interpolation) to single quotes and adds a lint rule to enforce the consistency in the future since we had a mix of both.
=> fix: double to single quotes and lint rule

CHANGELOG.md, lib/easypost.php, test/EasyPost/RequireTest.php
Removes `CreditCard` and `PaymentMethod` imports that no longer exist. This fixes an import bug when importing this library (instead of using the autoloader which doesn't raise this error).
Closes #211 
Adds a regression test by trying to manually import the library in our test suite (the test suite uses the auto loader which is why this wasn't caught.)
=> fix: extra imports and add regression test

test/EasyPost/Fixture.php, test/EasyPost/RequireTest.php, test/EasyPost/WebhookTest.php
Uses the new `event` fixture and clarifies the `require` test
=> fix: fixture and require tests

.github/workflows/ci.yml
Very simple PR that bumps the version of ubuntu used so we don't need to maintain it and removes a redundant composer step since `setup-php` will install/update composer for us already.
=> chore: improves CI runtime by removing redundant steps and bumping ubuntu

CHANGELOG.md, lib/EasyPost/Shipment.php, test/EasyPost/ShipmentTest.php
Adds support to specify an `$endShipperId` on the buy call of a shipment.
We cannot easily test this due to needing to buy in prod.
=> feat: adds support to specify endShipperId on the buy call of a Shipment

lib/easypost.php
Forgot to add the `Referral` import when it got added.
=> fix: add missing Referral class to imports

lib/EasyPost/Address.php, test/EasyPost/AddressTest.php, test/cassettes/addresses/verifyInvalid.yml
Removes some unreachable address verification code. If an error occurs during verification, we will fail earlier than this function in the stack (closer to the request) and therefore we don't need to check for the existence of the `address` key. I added a unit test to ensure that we still properly throw error when an invalid address is passed meaning this change doesn't affect user expectations.
Added a unit test for throwing errors on invalid address verifications
=> refactor: removes unreachable address verification code

CHANGELOG.md, composer.json, lib/EasyPost/EasyPost.php
=> chore: prepares v5.7.0 for release

.github/workflows/ci.yml, Makefile, README.md, composer.json, composer.lock, lib/EasyPost/EasyPostClient.php, lib/EasyPost/Exception/Error.php, lib/EasyPost/Http/Requestor.php, lib/EasyPost/Service/AddressService.php, lib/EasyPost/Service/BaseService.php, lib/EasyPost/Service/BatchService.php, lib/EasyPost/Service/BillingService.php, lib/EasyPost/Service/CarrierAccountService.php, lib/EasyPost/Service/OrderService.php, lib/EasyPost/Service/PickupService.php, lib/EasyPost/Service/ReferralCustomerService.php, lib/EasyPost/Service/ReportService.php, lib/EasyPost/Service/ShipmentService.php, lib/EasyPost/Service/TrackerService.php, lib/EasyPost/Service/UserService.php, lib/easypost.php, phpunit.xml.dist, test/EasyPost/EasyPostClientTest.php
- Drops support for PHP 7.3 and adds CI checks for PHP 8.2.
- This PR also fixes the test config so it could be more helpful in debugging future issues and I corrected various deprecation issues that sprang up when running on PHP 8.2.
- Finally, this PR removes the need to instantiate a Requestor object since there is no need to do that on every request and instead passes down the client object as a param, making that whole class static. This helps performance and most likely the segfault issue in the long run that I'll be investigating later.
Tested PHP 8.2 with a scratch file and it worked as expected.
=> chore: drop 7.3, add 8.2

Makefile, composer.lock, lib/EasyPost/EasyPostClient.php, lib/EasyPost/Exception/Api/ApiException.php, lib/EasyPost/Http/Requestor.php, test/EasyPost/EasyPostClientTest.php, test/EasyPost/Fixture.php
Fixes the recursion problems of the EasyPostClient object by only instantiating the service when needed instead of when a client is created and passing those infinitely down. 
Also fixes a few deprecation warnings that were missed previously due to suppressed output.
Dumped an EasyPostClient object to ensure the recursion was fixed, re-recorded a cassette locally to ensure that services/functions still get called as expected
=> fix: recursion issues with EasyPostClient, deprecation warnings

README.md, lib/EasyPost/Service/ReferralCustomerService.php
=> fix: typo in example and add TODO

lib/EasyPost/EasyPostObject.php, lib/EasyPost/Service/AddressService.php, lib/EasyPost/Util/InternalUtil.php
During a team convo about how we deserialize objects, I found there was still some leftover dead code from the rewrite that can safely be removed to simplify this function. These params are no longer used
- Tests pass
=> fix: cleanup convertToEasyPostObject

lib/EasyPost/Util/InternalUtil.php
Simple refactor to move large static lists of object and ID mappings to constants instead of rebuilding these lists in memory every time an object needs to be created - which is a lot. Will make memory much happier.
Tests pass
=> fix: make large lists constants instead of rebuilding them on every function call

lib/EasyPost/EasyPostObject.php, lib/EasyPost/Util/InternalUtil.php
The object mapping list was missing `Brand` and had a few extra items in the list that never come back in an `object` field via a response. Although they are local classes in this lib, the constant list they were a part of is to lookup a value based on what we get back from the API, which in these cases would never happen. Removed to tighten up the possible options.
- Tests pass
=> fix: object mapping, required return types of PHP magic functions

lib/EasyPost/Service/ReportService.php, test/EasyPost/EventTest.php, test/cassettes/events/retrieve_all_payloads.yml, test/cassettes/events/retrieve_payload.yml, test/cassettes/reports/all.yml, test/cassettes/reports/createCustomAdditionalColumnReport.yml, test/cassettes/reports/createCustomColumnReport.yml, test/cassettes/reports/createReport.yml, test/cassettes/reports/retrieveReport.yml
This PR fixes two things that have no production affect:
1. Unsuts the `type` in `params` when retrieving all reports. This just cleans up the URL that's hit a bit, was not broken
2. Finally tracked down why the test suite was ~10 seconds slower than it should have been, whoever added `payload` left some copy/pasta so thr check to see if the cassette existed so it wouldn't sleep was always true to sleep, now with cassettes present it won't unnecessarily sleep
- Updated tests/re-recorded affected cassettes
=> fix: event type param, payload test sleep

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php
=> chore: prepare v6.3.0 for release

lib/EasyPost/Constant/Constants.php, lib/EasyPost/EasyPostClient.php, lib/EasyPost/Http/Requestor.php, lib/EasyPost/Service/ReferralCustomerService.php, lib/EasyPost/Service/UserService.php, lib/EasyPost/Util/InternalUtil.php, lib/EasyPost/Util/Util.php, phpcs.xml, test/EasyPost/AddressTest.php, test/EasyPost/BatchTest.php, test/EasyPost/BetaReferralCustomerTest.php, test/EasyPost/BillingTest.php, test/EasyPost/CarrierAccountTest.php, test/EasyPost/EasyPostClientTest.php, test/EasyPost/ErrorTest.php, test/EasyPost/Fixture.php, test/EasyPost/Mocking/MockingUtility.php, test/EasyPost/ReferralCustomerTest.php, test/EasyPost/RefundTest.php, test/EasyPost/ShipmentTest.php, test/EasyPost/TestUtil.php, test/EasyPost/TrackerTest.php, test/EasyPost/UserTest.php, test/EasyPost/WebhookTest.php
Enforces a line length of 120 chars.
I meant to do this a year ago when we setup our styles but it slipped my mind and I finally had a second to come back to this.
=> fix: enforce line length of 120

lib/EasyPost/Exception/Api/ApiException.php, lib/EasyPost/Exception/General/EasyPostException.php
Fixes EasyPost/easypost-php#286
Fixes deprecation warnings when using PHP 8.1. Please see linked issue for details.
> Passing null to non-nullable internal function parameters is deprecated.
Source: https://www.php.net/releases/8.1/en.php
No additional testing is required. This does not add any new features or functionality. The existing test suite should catch any problems.
=> Fix deprecation warnings for null Exception message

CHANGELOG.md, README.md, lib/EasyPost/EasyPostClient.php, lib/EasyPost/Hook/EventHook.php, lib/EasyPost/Hook/RequestHook.php, lib/EasyPost/Hook/ResponseHook.php, lib/EasyPost/Http/Requestor.php, test/EasyPost/HookTest.php, test/cassettes/hooks/request.yml, test/cassettes/hooks/response.yml, test/cassettes/hooks/unsubscribe.yml
- Adds new `RequestHook` and `ResponseHook` events. (un)subscribe to them with the new `subscribeToRequestHook`, `subscribeToResponseHook`, `unsubscribeFromRequestHook`, or `unsubscribeFromResponseHook` methods of an `EasyPostClient`
Adds a new set of tests that subscribe to the hooks and assert details only exposed via the hooks (not the traditional deserialized objects)
Adds a test to ensure that unsubscribing works as intended (will raise an exception if still subscribed), A/B tested this to ensure it works.
=> feat: adds http request and response hooks

.github/workflows/ci.yml, Makefile, README.md, composer.json
Fixes coverage by ensuring we use PHP 8.2.9 for the 8.2 branch which corrects the previous segfaults.
See https://github.com/php-vcr/php-vcr/issues/373 for more details.
=> fix: coverage generation with PHP 8.2

CHANGELOG.md, lib/EasyPost/Constant/Constants.php
- FedEx SmartPost carrier account registration should hit `/register` endpoint for creation
=> [fix] FedEx Smartpost hits register endpoint

CHANGELOG.md, lib/EasyPost/Http/Requestor.php
- Fixes a bug that changed the timezone to UTC on each request without resetting it to the original timezone in use (closes #310)
Ran these added commands in the repl to make sure these work as expected.
=> fix: reset timezone to original (closes #310)

Makefile
Pins the docs binary. The docs binary had breaking changes in a non major release and when pulled in, the command we have doesn't work. Also the most recent version doesn't support PHP 7 which we still do
Generated docs locally
=> fix: pin docs binary in Makefile

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php, lib/EasyPost/Http/Requestor.php
Fixes a bug that globally reset the timezone to UTC instead of setting the timezone per-request (closes #310)
Tests worked great in catching a bug for conversion. Corrected and all green.
=> fix: UTC timezone bug for request/response timestamps

.github/workflows/ci.yml, CHANGELOG.md, README.md, composer.json, test/cassettes/addresses/all.yml
PHP 7.4 has been dead for 2 years and 8.0 is also EOL. Keeping with our policy to include only the most recently deprecated version, this drops support for PHP 7.4 and adds support for the just released 8.3. This also allows us to finally upgrade PHP VCR which now allows cassettes to be recorded with any supported PHP version (previously you could only record on 7.4 but replay on any version).
- Re-recorded a cassette to ensure VCR works
- Tested on every supported PHP version
=> chore: overhaul version matrix

CHANGELOG.md, lib/EasyPost/EasyPostClient.php, lib/EasyPost/Http/Requestor.php, test/cassettes/addresses/all.yml, test/cassettes/addresses/getNextPage.yml
We previously recreated the Guzzle Client on every request. This PR moves the creation of the HTTP client into the `EasyPostClient` object to ensure that back-to-back requests using the same EasyPostClient will reuse the same HTTP client to reduce memory consumption. There should be no user impact with this change.
Please note that although the HTTP client is now a publicly accessible property of the EasyPostClient, it is not intended to be replaced as no additional work has been made yet to allow this (see #318 for that initiative)
Closes #315
Re-recorded a cassette with two requests to ensure it works as expected
=> feat: persist the HTTP client inside of EasyPostClient

CHANGELOG.md, composer.lock, lib/EasyPost/User.php, test/EasyPost/UserTest.php, test/cassettes/users/beta_user_paginated_api_keys.yml, test/cassettes/users/user_paginated_api_keys.yml
- Adds new function `paginated_api_keys` to `User` to return a paginated list of API keys, rather than unpaginated from `api_keys`
**NOTE:** This beta function exists in the GA `User` class rather than in a separate `Beta\User` class because this method is an instance method. It would only be accessible on `Beta\User` objects, which wouldn't have any other of the existing functions that exist on the `User` object. They would either have to be entirely re-implemented or a converter between `User` and `Beta\User` would have to be introduced; both strategies would add extra overhead and require changes to the end-user's workflow.
More recent major versions of our library have effectively removed this issue by our re-architecture into services that make it easier to separate beta functions …
=> [FEAT] Beta `paginated_api_keys` function

CHANGELOG.md, lib/EasyPost/Service/BillingService.php, test/EasyPost/BillingTest.php
- Use payment method object type as fallback when determining type for fund, delete functions
- Update, add unit test to confirm legacy (by ID prefix) and new (by object type) both work to determine payment method type
=> [bug] Cannot determine payment method when funding/deleting

CHANGELOG.md, lib/EasyPost/EasyPostClient.php, lib/EasyPost/Service/ShipmentService.php, lib/EasyPost/Service/SmartRateService.php, lib/easypost.php, test/EasyPost/Fixture.php, test/EasyPost/ShipmentTest.php, test/EasyPost/SmartRateTest.php, test/cassettes/shipments/recommendShipDate.yml, test/cassettes/shipments/retrieveEstimatedDeliveryDate.yml, test/cassettes/smartrate/estimatedDeliveryDate.yml, test/cassettes/smartrate/recommendShipDate.yml
- Adds new `shipment.recommendShipDate`, `smartrate.recommendShipDate`, and `smartrate.estimateDeliveryDate` functions
Add new unit tests
=> Add new smartrate endpoints functions

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php
=> prep release v7.3.0

CHANGELOG.md, lib/EasyPost/AddressVerificationFieldError.php, lib/EasyPost/Exception/Api/ApiException.php, lib/EasyPost/Verification.php, lib/EasyPost/VerificationDetails.php, lib/EasyPost/Verifications.php, test/EasyPost/AddressTest.php, test/EasyPost/ErrorTest.php, test/cassettes/errors/errorsAlternativeFormat.yml
- Fixes error handling
- Corrects the type of `errors` property on an `ApiException` to allow for the alternative format
- Fixes a bug where you could not `prettyPrint` an error if it used the alternative format
- Corrects the `param` references to `property` references on all error models
- Adds new `AddressVerificationFieldError` for the `errors` property on a `Verification` model
- Adds missing `suggestion` property to `FieldError`
- Adds alternative error format test
- Adds address verification error test
=> fix: prettyPrint errors

CHANGELOG.md, lib/EasyPost/Constant/Constants.php, lib/EasyPost/Service/CarrierAccountService.php, test/EasyPost/CarrierAccountTest.php, test/cassettes/carrier_accounts/create_amazon.yml
=> feat: route AmazonShippingAccount on create

CHANGELOG.md, UPGRADE_GUIDE.md, composer.json, lib/EasyPost/Constant/Constants.php
=> chore: prepare v8.0.0 for release

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php, lib/EasyPost/Exception/Api/ApiException.php, lib/EasyPost/Http/Requestor.php, lib/EasyPost/Service/CarrierAccountService.php, test/cassettes/carrier_accounts/create_ups.yml, test/cassettes/carrier_accounts/update_ups.yml
=> fix: endpoint used for ups create/update
