EasyPost/easypost-php

lib/EasyPost/Address.php, lib/EasyPost/Batch.php, lib/EasyPost/CarrierAccount.php, lib/EasyPost/Container.php, lib/EasyPost/CustomsInfo.php, lib/EasyPost/CustomsItem.php, lib/EasyPost/EasyPost.php, lib/EasyPost/Error.php, lib/EasyPost/Event.php, lib/EasyPost/Fee.php, lib/EasyPost/Item.php, lib/EasyPost/Object.php, lib/EasyPost/Order.php, lib/EasyPost/Parcel.php, lib/EasyPost/Pickup.php, lib/EasyPost/PostageLabel.php, lib/EasyPost/Rate.php, lib/EasyPost/Refund.php, lib/EasyPost/Requestor.php, lib/EasyPost/Resource.php, lib/EasyPost/ScanForm.php, lib/EasyPost/Shipment.php, lib/EasyPost/Tracker.php, lib/EasyPost/User.php, lib/EasyPost/Util.php
docblocks are a great way to document code.
they are also great for IDEs and helping them with their autocomplete
and code analysis.
i did the best i could describing methods. most of them are self explanatory, and the ones I wasn’t sure on I put very general descriptions in. while it may be beneficial for one of the maintainers to go through again afterwards and put in better descriptions, this is a good starting point.
=> add docblocks

lib/EasyPost/Address.php, lib/EasyPost/Batch.php, lib/EasyPost/CarrierAccount.php, lib/EasyPost/Container.php, lib/EasyPost/CustomsInfo.php, lib/EasyPost/CustomsItem.php, lib/EasyPost/Event.php, lib/EasyPost/Fee.php, lib/EasyPost/Item.php, lib/EasyPost/ObjectResource.php, lib/EasyPost/Order.php, lib/EasyPost/Parcel.php, lib/EasyPost/Pickup.php, lib/EasyPost/PostageLabel.php, lib/EasyPost/Rate.php, lib/EasyPost/Refund.php, lib/EasyPost/Requestor.php, lib/EasyPost/ScanForm.php, lib/EasyPost/Shipment.php, lib/EasyPost/Tracker.php, lib/EasyPost/User.php, lib/easypost.php
Resource is a reserved word in PHP 7. This changes all instances of the name to ObjectResource.
=> Resource is a reserved word in PHP 7

examples/insurance.php, lib/EasyPost/Insurance.php, lib/EasyPost/Util.php, lib/easypost.php
@sawyer @att14 @victoryftw Seems like this is it?
=> add insurance to supported types

.gitignore, composer.json, test/EasyPost/Test/AddressTest.php, test/EasyPost/Test/ParcelTest.php, test/EasyPost/Test/ShipmentTest.php
Updated PHPUnit from v3.x to v8.x, tweaked single previously included unit test and added a Parcel and shipment unit test. More to come but this is ready to merge if approved.
Closes #68
=> Updated test suite, added more basic unit tests

README.md
This PR is dependent on #75 #74 #73 as it encompasses all the various changes from those PR's in this one.
Aside from new information, there is lots of info here that was clarified or cleaned up for better readability and a more straightforward setup.
=> Extensive README cleanup

.gitignore, .travis.yml, composer.json
Added travis.yml file for CI testing and updated composer.json with linting dependencies.
Closes #69
=> Added travis-ci testing & linting deps

lib/EasyPost/Util.php
The new shipment invoice report prefix needed to be added to the list which I've done so here.
=> Adding Shipment Invoice & Refund Report to Prefix & Type Lists

lib/EasyPost/User.php
Every CL but the PHP one allows users (child users) to be deleted. Added that functionality here.
=> Allow users to be deleted

lib/EasyPost/Event.php
Added the missing `retrieve` and `all` event methods.
=> Added missing event retrieve methods

lib/EasyPost/CustomsInfo.php, lib/EasyPost/CustomsItem.php, lib/EasyPost/Order.php
These 3 endpoints are not paginated and as such, should be removed due to low usage and performance.
=> Removed unpaginated "all" methods

examples/tracker_batch_create.php, lib/EasyPost/Tracker.php
This clarifies the create_list method and example and helps to address #91 or future questions about this.
=> Clarify the create_list method and example. Addresses #91

CHANGELOG.md, lib/EasyPost/Requestor.php
Adds the PHP version used to the `user-agent` header.
=> feat: adds the PHP version used to the user-agent header

CHANGELOG.md, UPGRADE_GUIDE.md
Adds an Upgrade Guide to the project.
=> chore: adds upgrade guide

lib/EasyPost/Report.php, test/cassettes/reports/all.yml, test/cassettes/reports/createCustomAdditionalColumnReport.yml, test/cassettes/reports/createCustomColumnReport.yml, test/cassettes/reports/createPaymentLogReport.yml, test/cassettes/reports/createRefundReport.yml, test/cassettes/reports/createShipmentInvoiceReport.yml, test/cassettes/reports/createShipmentReport.yml, test/cassettes/reports/createTrackerReport.yml, test/cassettes/reports/retrievePaymentLogReport.yml, test/cassettes/reports/retrieveRefundReport.yml, test/cassettes/reports/retrieveShipmentReport.yml, test/cassettes/reports/retrieveTrackerReport.yml
- Report columns go in JSON body rather than query params
- Re-record cassettes
=> Report `columns` and `additional_columns` sent via body rather than query

.github/workflows/ci.yml, .gitignore
This PR bumps `actions/checkout@v2` to `actions/checkout@v3`
=> update github action to v3.

lib/EasyPost/CustomsInfo.php
This PR adds missing property string for `declaration` in Customs Info
=> add property string for declaration in customs info.

lib/EasyPost/Address.php, test/EasyPost/AddressTest.php, test/EasyPost/Fixture.php, test/cassettes/addresses/all.yml, test/cassettes/addresses/create.yml, test/cassettes/addresses/createAndVerify.yml, test/cassettes/addresses/createVerify.yml, test/cassettes/addresses/createVerifyStrict.yml, test/cassettes/addresses/retrieve.yml, test/cassettes/addresses/verify.yml, test/cassettes/shipments/createWithIds.yml
This PR removes code that adds `strict` and `verify_strict` to the URL query when the API method is POST.  Small update the fixture and adjust the unit test.
re-record existing cassettes and all unit tests passed.
=> remove additional code that add params to URL query for post method.

.github/PULL_REQUEST_TEMPLATE.md
Swap the order of the pull request template.
N/A
=> Swap the PR template

CHANGELOG.md, README.md
Adds missing upgrade guide link to README and CHANGELOG
=> docs: add missing upgrade guide link

CHANGELOG.md, composer.json, lib/EasyPost/EasyPost.php
Prepares v5.1.1 for release
NA
=> chore: prepare v5.1.1 for release

lib/EasyPost/EasypostResource.php, lib/EasyPost/Report.php, lib/EasyPost/Requestor.php, lib/EasyPost/User.php
There is some old logic surrounding what functions require an API key and which don't (they all do at present). This PR cleans up that logic to avoid confusion and be more precise.
- Tests pass
=> chore: cleans up required API key logic

lib/easypost.php
Add missing import statement for `end_shipper`
None
=> add missing require import statement for end_shipper.

CHANGELOG.md, composer.json, composer.lock, lib/EasyPost/EasyPost.php
=> chore: prepare v5.2.0 for release

CHANGELOG.md, composer.json, lib/EasyPost/EasyPost.php
=> chore: prepare v5.2.1 for release

lib/EasyPost/PaymentMethod.php
Add the missing conditional statement to check if the id is null when retrieving payment methods.
=> add missing conditional statement to check if there is a payment method.

test/EasyPost/CreditCardTest.php
changed CreditCardFund test from 20 to 2000
=> Update CreditCardFund Test

lib/EasyPost/Billing.php, test/EasyPost/BillingTest.php
change the return type for the `fundWallet` and `deletePaymentMethod` in billing from empty response to true
N/a
=> change the return type for fund and delete in billing.

CHANGELOG.md, composer.json, lib/EasyPost/EasyPost.php
Prepares v5.3.0 for release.
Closes #181 
=> chore: prepares v5.3.0 for release

CHANGELOG.md, lib/EasyPost/Shipment.php, test/EasyPost/Fixture.php, test/EasyPost/ShipmentTest.php, test/cassettes/shipments/generateForm.yml
- Add form creation function on Shipment
- Add unit test and cassette for form creation
- Update CHANGELOG.md
=> Add generate forms functionality

CHANGELOG.md, composer.json, lib/EasyPost/EasyPost.php
=> chore: prepares v5.4.0 for release

.gitignore
=> chore: ignores env file

test/EasyPost/AddressTest.php, test/cassettes/addresses/createAndVerify.yml
Removes a dead param from one of the address verification tests.
=> chore: removes bogus verify param in test

CHANGELOG.md, composer.json, lib/EasyPost/EasyPost.php
=> chore: prepares v5.5.0 for release

.github/workflows/ci.yml, Makefile, README.md, composer.json, composer.lock
Retains current `composer` commands while providing the more traditional "EasyPost" Makefile targets as well that our other libs provide.
Updated the README with new command instructions.
- Ran each of these commands to ensure they work as intended
=> chore: introduces Makefile for consistent command usage

composer.json, lib/EasyPost/EasyPost.php
=> chore: prepare v5.5.1 for release

CHANGELOG.md, composer.json, lib/EasyPost/EasyPost.php
=> chore: prepares v5.6.0 for release

CHANGELOG.md, lib/EasyPost/Referral.php, lib/EasyPost/Requestor.php, test/EasyPost/ReferralTest.php, test/bootstrap.php, test/cassettes/referrals/addCreditCard.yml, test/cassettes/referrals/all.yml, test/cassettes/referrals/create.yml, test/cassettes/referrals/updateEmail.yml
- Adds Partner White Label (Referral) Support
- Adds ability to create a referral user
- Adds ability to update a referral user's email
- Adds ability to retrieve all referral users
- Adds ability to add a credit card to a referral user's account
Adds tests for each new function
=> feat: adds support for Partner White Label (Referrals)

.github/workflows/ci.yml, test/bootstrap.php
I incorrectly titled a helper function which is corrected here.
Coverage is now enforce on CI.
=> Fix test helper

lib/EasyPost/Requestor.php
Tiny PR to correct the error comment as the change is now sticking around
=> fix: error comment

.github/workflows/ci.yml, README.md, composer.json, composer.lock
Adds coveralls for coverage reporting
=> feat: adds coveralls

.github/workflows/ci.yml, Makefile, composer.json
Fixes the path of the output clover file so it can be writable on CI
Unfortunately this stuff can't be tested till it hits the master branch. Luckily it affects nothing meaningful if misconfigured.
=> fix: coverage path

CHANGELOG.md, composer.json, lib/EasyPost/EasyPost.php
=> chore: prepare v5.8.0 for release

Makefile, lib/EasyPost/Billing.php, lib/EasyPost/Referral.php, lib/EasyPost/Tracker.php, test/EasyPost/ReferralTest.php, test/EasyPost/TrackerTest.php, test/EasyPost/UserTest.php
Functions that don't have a response on return will return void
Updated tests
=> fix!: functions without a response return void

lib/EasyPost/User.php, lib/EasyPost/Util.php, test/EasyPost/UserTest.php, test/cassettes/users/allApiKeys.yml, test/cassettes/users/authenticatedUserApiKeys.yml, test/cassettes/users/childUserApiKeys.yml
Removes the double wrapping of API key responses to keep the behavior consistent with other libs and so we can properly assert that objects are what they are supposed to be.
Updated unit tests to check for types
=> fix: double wrapping of API key responses

CHANGELOG.md, UPGRADE_GUIDE.md, composer.json, composer.lock
Prepares v6.0.0 for release, adds upgrade guide entry.
=> chore: prepare v6.0.0 for release

CHANGELOG.md, composer.json, composer.lock, lib/EasyPost/Constant/Constants.php
Forgot to append `rc1` to the versions since we aren't releasing the final version yet.
=> fix: version to be release candidate

README.md, lib/EasyPost/EasyPostClient.php, lib/EasyPost/Service/BetaReferralCustomerService.php, test/EasyPost/BetaReferralCustomerTest.php, test/cassettes/beta/referral_customers/addPaymentMethod.yml, test/cassettes/beta/referral_customers/refundByAmount.yml, test/cassettes/beta/referral_customers/refundByPaymentLog.yml
- Adds new billing functionality for ReferralCustomer users
- `addPaymentMethod` can add a pre-existing Stripe bank account or credit card to your EasyPost account
- `refundByAmount` refunds your wallet by a dollar amount
- `refundByPaymentLog` refunds you wallet by a PaymentLog ID
Adds new tests that assert the proper errors since we won't have valid data for any of this.
=> feat: adds new beta refund and add payment method functions

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php
=> chore: prepare v6.1.0 for release

test/EasyPost/ShipmentTest.php, test/cassettes/shipments/buyShipmentWithEndShipper.yml
- Add unit test for buying shipment with end shipper
- New unit test, cassette
=> Add unit test for buying shipment with end shipper

CHANGELOG.md, lib/EasyPost/Service/PickupService.php, test/EasyPost/PickupTest.php, test/cassettes/pickups/all.yml
- New function to retrieve all pickups
- New unit test, cassettes
=> feat: New function to retrieve all pickups

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php
=> chore: prepare v6.2.0 for release

README.md
=> docs: adds link to php docs

test/EasyPost/RefundTest.php, test/cassettes/refunds/create.yml
Sends the tracking codes as a list instead of string
=> fix: refund test

CHANGELOG.md, lib/EasyPost/Http/Requestor.php
=> Correct HTTP 403 to ForbiddenException

Makefile, composer.json
This should be enforced at the root, not in the Makefile
=> chore: move coverage check from Makefile to composer

lib/EasyPost/Tracker.php, lib/EasyPost/TrackingDetail.php, test/bootstrap.php
Adds the missing `status_detail` property to the `Tracker` and `TrackingDetail` class.
Closes #274
=> fix: add status_detail property to TrackingDetail class (closes #274)

docs/classes/EasyPost-Constant-Constants.html, docs/classes/EasyPost-EasyPostClient.html, docs/classes/EasyPost-Http-Requestor.html, docs/classes/EasyPost-Parcel.html, docs/classes/EasyPost-Service-BetaRateService.html, docs/classes/EasyPost-Tracker.html, docs/classes/EasyPost-TrackingDetail.html, docs/classes/EasyPost-Util-InternalUtil.html, docs/classes/EasyPost-Util-Util.html, docs/files/lib-easypost-service-betarateservice.html, docs/files/lib-easypost-util-internalutil.html, docs/indices/files.html, docs/js/searchIndex.js, docs/namespaces/easypost-util.html, docs/packages/Application.html, lib/EasyPost/Parcel.php
Fixes typo in `EasyPost\Parcel` property PHPDoc
Closes #276 
`EASYPOST_TEST_API_KEY=123... EASYPOST_PROD_API_KEY=123... make test`
> OK (145 tests, 356 assertions)
Unit test for Parcel already includes an assertion on weight, no new unit tests added.
=> Correct spelling of Parcel weight property (closes #276)

README.md
=> Fix spelling error in README example

README.md, UPGRADE_GUIDE.md
Adds support policy to README.
Closes #270 
=> chore: add support section to README, deprecate old versions

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php
=> chore: prepare v6.3.1 for release

composer.json, lib/EasyPost/Service/BaseService.php, lib/EasyPost/Service/EventService.php, lib/EasyPost/Service/InsuranceService.php, lib/EasyPost/Service/PickupService.php, lib/EasyPost/Service/ReferralCustomerService.php, lib/EasyPost/Service/RefundService.php, lib/EasyPost/Service/ReportService.php, lib/EasyPost/Service/ScanFormService.php, lib/EasyPost/Service/ShipmentService.php, lib/EasyPost/Service/TrackerService.php
- fix bugs for `get_next_page` functions for Tracker and Shipment
- add `tracking_code` and `carrier` in the query string for Tracker `get_next_page` function
- add `purchased` and `include_children` in the query string for Shipment `get_next_page` function
=> fix bugs for "get_next_page" functions for Tracker and Shipment

CHANGELOG.md, lib/EasyPost/Service/ShipmentService.php, test/EasyPost/ShipmentTest.php, test/cassettes/shipments/retrieveEstimatedDeliveryDate.yml
Adds `retrieveEstimatedDeliveryDate` function to Shipment class
Adds a new test
=> feat: adds retrieveEstimatedDeliveryDate function

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php, test/EasyPost/Fixture.php, test/EasyPost/ShipmentTest.php
=> chore: prepare v6.6.0 for release

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php
=> chore: prepare v6.7.0 for release

README.md
Per #302, clarifies the install instructions
=> docs: clarify requiring comments on README

CHANGELOG.md, lib/EasyPost/Exception/Api/BadRequestException.php, lib/EasyPost/Http/Requestor.php, lib/easypost.php
Maps 400 status codes to new `BadRequestException` class
=> feat: maps 400 status codes to BadRequestException class

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php
=> chore: prepare v6.8.0 for release

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php
=> [chore] Prep release

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php
=> chore: prepare v6.9.0 for release

CHANGELOG.md, lib/EasyPost/Service/BetaReferralCustomerService.php, lib/EasyPost/Service/BillingService.php, lib/EasyPost/Service/ReferralCustomerService.php
- Renames `primaryOrSecondary` to `priority` to match the API name for the parameter
=> fix: rename primaryOrSecondary to priority

CHANGELOG.md, UPGRADE_GUIDE.md, composer.json, lib/EasyPost/Constant/Constants.php, lib/EasyPost/Service/ReferralCustomerService.php, test/EasyPost/ReferralCustomerTest.php
- Bumps version
- Adds entry to upgrade guide
- Fixes a lone TODO that was missed and actionable
=> chore: prepare v7.0.0 for release

test/EasyPost/AddressTest.php, test/cassettes/addresses/createAndVerify.yml, test/cassettes/addresses/createVerify.yml, test/cassettes/addresses/createVerifyArray.yml
See https://github.com/EasyPost/easypost-csharp/pull/540 for more details.
- Update examples submodule for new "incorrect address" fixture
- Alter address verification tests to better test target functionality
- Update unit tests, re-record cassettes as needed
- Suppress linting errors due to undefined sub-properties
=> [chore] Fix address verification unit tests

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php
- Bump version number
- Update changelog
=> [chore] Prep for 7.1.0 release

CHANGELOG.md, composer.json, lib/EasyPost/EasyPost.php, lib/EasyPost/User.php
- Bump version number
- Clarify that beta feature is locked to approved users only
=> [chore] Prep for v5.9.0 release

CHANGELOG.md, lib/EasyPost/Service/InsuranceService.php, test/EasyPost/InsuranceTest.php, test/cassettes/insurance/refund.yml
Add refund function in insurance service
Added a unit test
=> Add refund function in insurance service

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php
=> prep release v7.2.0

CHANGELOG.md, Makefile, lib/EasyPost/Constant/Constants.php, lib/EasyPost/Service/CarrierAccountService.php, test/EasyPost/CarrierAccountTest.php, test/cassettes/carrier_accounts/create_ups.yml, test/cassettes/carrier_accounts/update_ups.yml
Update CarrierService update and create method to account UPS endpoints
Add unit tests
=> Update CarrierService update and create method to account UPS endpoints

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php
=> prep release v7.4.0

CHANGELOG.md, lib/EasyPost/Service/UserService.php, test/cassettes/users/getNextPageOfChildren.yml
Pagination for listing child users needs to use "after_id", not "before_id"
=> [bug] Fix parameters for child user pagination

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php
=> chore: prep v7.4.1 for release

CHANGELOG.md, composer.json, lib/EasyPost/Constant/Constants.php
=> chore: prep v7.4.2 for release

CHANGELOG.md, lib/EasyPost/Service/BetaReferralCustomerService.php, lib/EasyPost/Service/ReferralCustomerService.php, test/EasyPost/BetaReferralCustomerTest.php, test/EasyPost/BillingTest.php, test/EasyPost/Fixture.php, test/EasyPost/ReferralCustomerTest.php, test/cassettes/beta/referral_customers/testCreateBankAccountClientSecret.yml, test/cassettes/beta/referral_customers/testCreateCreditCardClientSecret.yml, test/cassettes/referral_customers/addBankAccountFromStripe.yml, test/cassettes/referral_customers/addCreditCardFromStripe.yml
- Adds the following functions to assist ReferralCustomers add credit cards and bank accounts:
- `betaReferralCustomer.createCreditCardClientSecret`
- `betaReferralCustomer.createBankAccountClientSecret`
- `referralCustomer.addCreditCardFromStripe`
- `referralCustomer.addBankAccountFromStripe`
- Adds new tests for each function
=> feat: referral customer billing functions

CHANGELOG.md, lib/EasyPost/Tracker.php, lib/EasyPost/TrackingDetail.php
=> feat: add missing properties to Tracker and TrackingDetail models

CHANGELOG.md, composer.json, lib/EasyPost/Claim.php
=> chore: add reference to claims
